
/**
 * @file uds.h
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

#ifndef __MAIN_MODULE_UDS_H__
#define __MAIN_MODULE_UDS_H__

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#define UDS_NUM_VARS                         20

#define UDS_ID_DUMMY_TEST_UDS              0x00
#define UDS_ID_SDC_MAIN_STATUS             0x01
#define UDS_ID_SDC_CENTER_STOP_STATUS      0x02
#define UDS_ID_SDC_INERTIA_SW_STATUS       0x03
#define UDS_ID_SDC_BOTS_STAT               0x04
#define UDS_ID_SDC_BSPD_STAT               0x05
#define UDS_ID_SDC_BMS_STAT                0x06
#define UDS_ID_SDC_IMD_STAT                0x07
#define UDS_ID_SDC_R_ESTOP_STAT            0x08
#define UDS_ID_SDC_L_ESTOP_STAT            0x09
#define UDS_ID_SDC_HVD_STAT                0x0a
#define UDS_ID_SDC_REAR_HUB_STAT           0x0b
#define UDS_ID_SDC_TSMS_STAT               0x0c
#define UDS_ID_SDC_PCHG_OUT_STAT           0x0d
#define UDS_ID_DAQ_BUZZER                  0x0e
#define UDS_ID_DAQ_BRAKE                   0x0f
#define UDS_ID_DAQ_CONSTANT_TORQUE         0x10
#define UDS_ID_CONST_TQ_VAL                0x11
#define UDS_ID_DAQ_BUZZER_BRAKE_STATUS     0x12
#define UDS_ID_CAN_ESR                     0x13

void uds_init(void);
void uds_frame_send(uint64_t data);
void uds_command_main_module_CALLBACK(uint64_t payload);

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#endif // __MAIN_MODULE_UDS_H__
