
/**
 * @file uds.c
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#include "common/uds/uds.h"
#include "uds.h"
#include "can_parse.h"

/* Module includes */
#include "cooling.h"
#include "main.h"
#include "car.h"

#define UVAR(x) ((uint32_t)(&(x)))

uds_variable_t uds_tracked_vars[UDS_NUM_VARS] = {
    { .id=UDS_ID_DUMMY_TEST_UDS, .addr=UVAR(dummy_test_uds), .len=32, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_SDC_MAIN_STATUS, .addr=UVAR(sdc_mux.main_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_CENTER_STOP_STATUS, .addr=UVAR(sdc_mux.c_stop_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_INERTIA_SW_STATUS, .addr=UVAR(sdc_mux.inertia_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_BOTS_STAT, .addr=UVAR(sdc_mux.bots_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_BSPD_STAT, .addr=UVAR(sdc_mux.bspd_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_BMS_STAT, .addr=UVAR(sdc_mux.bms_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_IMD_STAT, .addr=UVAR(sdc_mux.imd_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_R_ESTOP_STAT, .addr=UVAR(sdc_mux.r_stop_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_L_ESTOP_STAT, .addr=UVAR(sdc_mux.l_stop_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_HVD_STAT, .addr=UVAR(sdc_mux.hvd_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_REAR_HUB_STAT, .addr=UVAR(sdc_mux.r_hub_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_TSMS_STAT, .addr=UVAR(sdc_mux.tsms_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_SDC_PCHG_OUT_STAT, .addr=UVAR(sdc_mux.pchg_out_stat), .len=1, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_DAQ_BUZZER, .addr=UVAR(daq_buzzer), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_DAQ_BRAKE, .addr=UVAR(daq_brake), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_DAQ_CONSTANT_TORQUE, .addr=UVAR(daq_constant_tq), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_CONST_TQ_VAL, .addr=UVAR(const_tq_val), .len=8, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_DAQ_BUZZER_BRAKE_STATUS, .addr=UVAR(buzzer_brake_fault), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_CAN_ESR, .addr=UVAR(CAN1->ESR), .len=32, .perm=(UDS_VAR_READ_FLAG)},
};

void uds_init(void)
{
    uds_init_base(uds_tracked_vars, UDS_NUM_VARS);
}

void uds_frame_send(uint64_t data)
{
    SEND_UDS_RESPONSE_MAIN_MODULE(data);
}

void uds_command_main_module_CALLBACK(uint64_t payload)
{
    uint8_t cmd = payload & 0xff;
    uint64_t data = (payload >> 8); /* store u48 in u64 */
    uds_handle_command(cmd, data);
}

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */
