
/**
 * @file uds.h
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

#ifndef __A_BOX_UDS_H__
#define __A_BOX_UDS_H__

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#define UDS_NUM_VARS                         12

#define UDS_ID_CHARGE_REQUEST_USER         0x00
#define UDS_ID_USER_CHARGE_CURRENT_REQUEST 0x01
#define UDS_ID_USER_CHARGE_VOLTAGE_REQUEST 0x02
#define UDS_ID_TMU_DAQ_OVERRIDE            0x03
#define UDS_ID_TMU_DAQ_THERM               0x04
#define UDS_ID_TMU_1                       0x05
#define UDS_ID_TMU_2                       0x06
#define UDS_ID_TMU_3                       0x07
#define UDS_ID_TMU_4                       0x08
#define UDS_ID_BMS_DAQ_OVERRIDE            0x09
#define UDS_ID_BMS_DAQ_STAT                0x0a
#define UDS_ID_CAN_ESR                     0x0b

void uds_init(void);
void uds_frame_send(uint64_t data);
void uds_command_a_box_CALLBACK(uint64_t payload);

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#endif // __A_BOX_UDS_H__
