
/**
 * @file uds.c
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#include "common/uds/uds.h"
#include "uds.h"
#include "can_parse.h"

/* Module includes */
#include "orion.h"
#include "tmu.h"
#include "main.h"

#define UVAR(x) ((uint32_t)(&(x)))

uds_variable_t uds_tracked_vars[UDS_NUM_VARS] = {
    { .id=UDS_ID_CHARGE_REQUEST_USER, .addr=UVAR(charge_request_user), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_USER_CHARGE_CURRENT_REQUEST, .addr=UVAR(user_charge_current_request), .len=16, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_USER_CHARGE_VOLTAGE_REQUEST, .addr=UVAR(user_charge_voltage_request), .len=16, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_TMU_DAQ_OVERRIDE, .addr=UVAR(tmu_daq_override), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_TMU_DAQ_THERM, .addr=UVAR(tmu_daq_therm), .len=4, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_TMU_1, .addr=UVAR(adc_readings.tmu_1), .len=12, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_TMU_2, .addr=UVAR(adc_readings.tmu_2), .len=12, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_TMU_3, .addr=UVAR(adc_readings.tmu_3), .len=12, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_TMU_4, .addr=UVAR(adc_readings.tmu_4), .len=12, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_BMS_DAQ_OVERRIDE, .addr=UVAR(bms_daq_override), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_BMS_DAQ_STAT, .addr=UVAR(bms_daq_stat), .len=1, .perm=(UDS_VAR_READ_FLAG | UDS_VAR_WRITE_FLAG)},
    { .id=UDS_ID_CAN_ESR, .addr=UVAR(CAN1->ESR), .len=32, .perm=(UDS_VAR_READ_FLAG)},
};

void uds_init(void)
{
    uds_init_base(uds_tracked_vars, UDS_NUM_VARS);
}

void uds_frame_send(uint64_t data)
{
    SEND_UDS_RESPONSE_A_BOX(data);
}

void uds_command_a_box_CALLBACK(uint64_t payload)
{
    uint8_t cmd = payload & 0xff;
    uint64_t data = (payload >> 8); /* store u48 in u64 */
    uds_handle_command(cmd, data);
}

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */
