
/**
 * @file uds.h
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

#ifndef __PDU_UDS_H__
#define __PDU_UDS_H__

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#define UDS_NUM_VARS                         4

#define UDS_ID_LV_24_V_SENSE               0x00
#define UDS_ID_LV_5_V_SENSE                0x01
#define UDS_ID_LV_3V3_V_SENSE              0x02
#define UDS_ID_CAN_ESR                     0x03

void uds_init(void);
void uds_frame_send(uint64_t data);
void uds_command_pdu_CALLBACK(uint64_t payload);

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#endif // __PDU_UDS_H__
