
/**
 * @file uds.c
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#include "common/uds/uds.h"
#include "uds.h"
#include "can_parse.h"

/* Module includes */
#include "main.h"

#define UVAR(x) ((uint32_t)(&(x)))

uds_variable_t uds_tracked_vars[UDS_NUM_VARS] = {
    { .id=UDS_ID_LV_24_V_SENSE, .addr=UVAR(adc_readings.lv_24_v_sense), .len=12, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_LV_5_V_SENSE, .addr=UVAR(adc_readings.lv_5_v_sense), .len=12, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_LV_3V3_V_SENSE, .addr=UVAR(adc_readings.lv_3v3_v_sense), .len=12, .perm=(UDS_VAR_READ_FLAG)},
    { .id=UDS_ID_CAN_ESR, .addr=UVAR(CAN1->ESR), .len=32, .perm=(UDS_VAR_READ_FLAG)},
};

void uds_init(void)
{
    uds_init_base(uds_tracked_vars, UDS_NUM_VARS);
}

void uds_frame_send(uint64_t data)
{
    SEND_UDS_RESPONSE_PDU(data);
}

void uds_command_pdu_CALLBACK(uint64_t payload)
{
    uint8_t cmd = payload & 0xff;
    uint64_t data = (payload >> 8); /* store u48 in u64 */
    uds_handle_command(cmd, data);
}

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */
