
/**
 * @file uds.c
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#include "common/uds/uds.h"
#include "uds.h"
#include "can_parse.h"

/* Module includes */
#include "main.h"
#include "daq_hub.h"

#define UVAR(x) ((uint32_t)(&(x)))

uds_variable_t uds_tracked_vars[UDS_NUM_VARS] = {
    { .id=UDS_ID_ETH_STATE, .addr=UVAR(dh.eth_state), .len=8, .perm=(UDS_VAR_READ_FLAG)},
};

void uds_init(void)
{
    uds_init_base(uds_tracked_vars, UDS_NUM_VARS);
}

// Override send method for daq
#if 0
void uds_frame_send(uint64_t data)
{
    SEND_UDS_RESPONSE_DAQ(data);
}
#endif

void uds_command_daq_CALLBACK(uint64_t payload)
{
    uint8_t cmd = payload & 0xff;
    uint64_t data = (payload >> 8); /* store u48 in u64 */
    uds_handle_command(cmd, data);
}

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */
