
/**
 * @file uds.h
 * @author Eileen Yoon (eyn@purdue.edu)
 * @brief  Unified Diagnostics Services (UDS)
 * @version 0.1
 * @date 2024-12-18
 *
 * @copyright Copyright (c) 2024
 *
 */

#ifndef __TORQUE_VECTOR_UDS_H__
#define __TORQUE_VECTOR_UDS_H__

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#define UDS_NUM_VARS                         0


void uds_init(void);
void uds_frame_send(uint64_t data);
void uds_command_torque_vector_CALLBACK(uint64_t payload);

/* THIS FILE WAS AUTOGENERATED BY common/daq/generation/gen_embedded_daq.py */
/* DO NOT EDIT */
/* ADD/EDIT VARIABLES IN THE JSON common/daq/generation/daq_config.json INSTEAD */

#endif // __TORQUE_VECTOR_UDS_H__
